name: Deploy

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Installing dependencies
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install

    - name: Building project
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: build
      env:
        CI: ''

    - name: Running tests
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: test

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./build
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./build

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
