name: Check PR

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Installing dependencies
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install

    - name: Building project
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: build
      env:
        CI: ''

    - name: Running tests
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: test
